In [40]:
import numpy as np

In [41]:
arr = np.array([1,2,3,4,5,6])

In [42]:
arr

array([1, 2, 3, 4, 5, 6])

In [43]:
arr1 = np.array([1,3.45,"Hulash"])

In [44]:
arr1

array(['1', '3.45', 'Hulash'], dtype='<U32')

In [45]:
# creating numpy array using list

a = [[1,2,3],[4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [46]:
arr = np.array(a)

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr.shape


(2, 3)

In [49]:
# creating zeros with only zeros

array_of_zeros = np.zeros((3,5))

In [50]:
array_of_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
arr_ones = np.ones([5,6])

In [52]:
arr_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [53]:
np.full([4,5], 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [54]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
np.random.seed(42)

In [56]:
arr = np.random.randint(0,10, size = (3,6))

In [57]:
arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7]], dtype=int32)

In [58]:
arr.shape

(3, 6)

In [59]:
arr.ndim

2

In [60]:
arr.size

18

In [61]:
arr.dtype

dtype('int32')

In [62]:
arr.itemsize

4

In [63]:
arr.nbytes

72

In [64]:
arr.T

array([[6, 2, 7],
       [3, 6, 2],
       [7, 7, 5],
       [4, 4, 4],
       [6, 3, 1],
       [9, 7, 7]], dtype=int32)

In [65]:
# Indexing and slicing

arr = np.random.randint(1,50, size = (6,4))

In [66]:
arr

array([[44, 30, 38,  2],
       [21, 33, 12, 22],
       [44, 25, 49, 27],
       [42, 28, 16, 15],
       [47, 44,  3, 37],
       [ 7, 21,  9, 39]], dtype=int32)

In [67]:
# indexing and slicing in 2d arrays
arr[0]

array([44, 30, 38,  2], dtype=int32)

In [68]:
arr[0:2]

array([[44, 30, 38,  2],
       [21, 33, 12, 22]], dtype=int32)

In [69]:
arr[2:]

array([[44, 25, 49, 27],
       [42, 28, 16, 15],
       [47, 44,  3, 37],
       [ 7, 21,  9, 39]], dtype=int32)

In [70]:
arr[2,2]

np.int32(49)

In [71]:
arr[2:5,1:]

array([[25, 49, 27],
       [28, 16, 15],
       [44,  3, 37]], dtype=int32)

In [72]:
arr


array([[44, 30, 38,  2],
       [21, 33, 12, 22],
       [44, 25, 49, 27],
       [42, 28, 16, 15],
       [47, 44,  3, 37],
       [ 7, 21,  9, 39]], dtype=int32)

In [73]:
arr > 5

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [74]:
arr > 60


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])